# claude_api/client.py

from typing import Literal
from anthropic import AsyncAnthropic
from .config import ANTHROPIC_API_KEY

# Supported Claude models for type safety
ClaudeModel = Literal["claude-sonnet-4-5", "claude-haiku-4-5"]

# Global reusable async client instance
_client = AsyncAnthropic(api_key=ANTHROPIC_API_KEY)


async def ask_raw(
    prompt: str,
    model: ClaudeModel = "claude-sonnet-4-5",
    max_tokens: int = 800,
) -> str:
    """
    Send a raw text prompt to Claude and return the response as plain text.

    Args:
        prompt (str): The input text to send to Claude.
        model (ClaudeModel): Claude model to use.
        max_tokens (int): Maximum number of tokens to generate.

    Returns:
        str: The textual response generated by Claude.
    """
    msg = await _client.messages.create(
        model=model,
        max_tokens=max_tokens,
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
    )

    # Claude returns a list of content blocks (text, images, etc.)
    # For now we extract the first text block.
    block = msg.content[0]
    return getattr(block, "text", str(block))